### ISSUE TITLE
[FEATURE] create a page layout 

### ISSUE THREAD

**Issue by devvsakib** [FrancescoXX/rustcrab#126]
**Description**

Our project layout and UI should be consistent. Create a component called PageLayout and use it for all pages.

**Comment by dvpavan-kumar** [comment]
Hi @devvsakib  could you please explain bit more do we have to change structure of books, devtools ..in app 
<img width="308" alt="image" src="https://github.com/user-attachments/assets/04037217-48e4-42ec-afe8-31e3476d34a7">

**Comment by felixoder** [comment]
@dvpavan-kumar It's very simple just look that we have used same types of components simultaneously in our SPA app like ProjectSection , DsaSection and so on actually they're fetching the details from the xyz .ts and show them up.

Create a component that can do that dynamically. So that we can use that in our application to reuse those.

Also do one thing there is a section of /app dir which redirects to a page where a certain filter option is there. We are also using that mul time so also create a comp for that and reuse that!
 That'll make this app optimised and well structured!

**Comment by felixoder** [comment]
@dvpavan-kumar It's very simple just look that we have used same types of components simultaneously in our SPA app like ProjectSection , DsaSection and so on actually they're fetching the details from the xyz .ts and show them up.

Create a component that can do that dynamically. So that we can use that in our application to reuse those.

Also do one thing there is a section of /app dir which redirects to a page where a certain filter option is there. We are also using that mul time so also create a comp for that and reuse that!
 That'll make this app optimised and well structured!
